export {Header} from './header/Header'
export {Profile} from './profile/Profile'
export {Education} from './education/Education'
export {Skills} from './skills/Skills'
//export {Picture} from '../../public/picture/Picture'
